### ISSUE TITLE
Merge related issues because of some bug in Jgit 3.0

### ISSUE THREAD

**Issue by shivarajugowda** [shivarajugowda/verigreen#6]
I am using git 2.04 with this version I see JGIT 3.0 throws an error when switching a branch or pulling in the changes from the remote branch. Seems to be some incompatibility with GIT versions. Updating to JGIT 3.5 takes care of the problem. 

If you use 3.5, you will also be forced to specify the CredentialsProvider, so add framework to input username/password for git.

{code}
[integrate]$ /home/xxxx/tmp/JGIT/jgit-stable-3.0/org.eclipse.jgit.pgm/target/jgit checkout vg_1c5a16b_shivshi_new_1478640071174
org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
xxx/xxx/xx/xx.java
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:244)
	at org.eclipse.jgit.pgm.Checkout.run(Checkout.java:86)
	at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:174)
	at org.eclipse.jgit.pgm.Main.execute(Main.java:213)
	at org.eclipse.jgit.pgm.Main.run(Main.java:121)
	at org.eclipse.jgit.pgm.Main.main(Main.java:95)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
xxx/xxx/xx/xx.java
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:411)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:391)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:240)
	... 5 more

{code}

**Comment by shivarajugowda** [comment]
Added "gitUser" and "gitPassword" properties. Updated to use JGIT 3.5.
